on:
  pull_request:
  push:
    branches:
      - feature/dagger-ci

jobs:
  textlint-ja:
    name: lint documents
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
      - name: go get
        run: go get -v
          working-directory: dagger
      - name: run dagger ci
        run: go run main.go
          working-directory: dagger
